# Generated by Django 3.1.5 on 2021-01-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cod',
            new_name='cod_available',
        ),
    ]
