# Generated by Django 3.1.5 on 2021-01-19 04:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mainapp', '0005_auto_20210119_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_item',
            new_name='Cart',
        ),
    ]
