# Generated by Django 3.1.5 on 2021-01-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_catagory_garment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='garment_type',
            field=models.CharField(blank=True, choices=[('M', 'Mens'), ('W', 'Womens'), ('K', 'Kids'), ('O', 'Other')], max_length=1),
        ),
    ]
