# Generated by Django 3.1.5 on 2021-01-24 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mainapp', '0010_auto_20210120_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=150)),
                ('phone', models.IntegerField(max_length=10)),
                ('alt_phone', models.IntegerField(max_length=10, null=True)),
                ('landmark', models.TextField(max_length=150)),
                ('town', models.TextField(max_length=50)),
                ('address_type', models.CharField(blank=True, choices=[('Office', 'Office'), ('Home', 'Home'), ('Commercial', 'Commercial')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
